// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfTlH7FP0cNKbCu1RF-48u7KHA3cLihg',
    appId: '1:964377082915:web:f699f9c162958a6abd4596',
    messagingSenderId: '964377082915',
    projectId: 'app-shoes-ecom',
    authDomain: 'app-shoes-ecom.firebaseapp.com',
    storageBucket: 'app-shoes-ecom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuMSt9i7cEjPc0FJxRnR-3TNMjrFaK318',
    appId: '1:964377082915:android:1673221012965edfbd4596',
    messagingSenderId: '964377082915',
    projectId: 'app-shoes-ecom',
    storageBucket: 'app-shoes-ecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_RxkblVJYyZ9GJcUFD70Q3zlKfWbjQeQ',
    appId: '1:964377082915:ios:d0c81ba7de0e0d5fbd4596',
    messagingSenderId: '964377082915',
    projectId: 'app-shoes-ecom',
    storageBucket: 'app-shoes-ecom.appspot.com',
    iosBundleId: 'com.example.appShoesEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_RxkblVJYyZ9GJcUFD70Q3zlKfWbjQeQ',
    appId: '1:964377082915:ios:79e0867fe728601ebd4596',
    messagingSenderId: '964377082915',
    projectId: 'app-shoes-ecom',
    storageBucket: 'app-shoes-ecom.appspot.com',
    iosBundleId: 'com.example.appShoesEcommerce.RunnerTests',
  );
}
